# 日志配置
# 1.console 控制台日志格式 %d 表示时间 ，%msg 表示内容，%n 表示换行
# 2.path  日志存放位置
# 3.file  日志存放位置，并制定文件名称
# 4.level 等级，可以针对类进行设置
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: D:\word\log\sell.log
#  level:
#    com.xiaoming.sell.LoggerTest: debug
#  path: D:\word\log
